apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - prometheus/alerts-rule/alerts.yml
  - prometheus/alerts-rule/serviceMonitor.yml
  - prometheus/alertmanager/email-secrets.yml
  - prometheus/alertmanager/alertmangerconfig.yml
  - grafana/observability-ingress.yaml
