grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClassName: longhorn # gp2
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
prometheus:
  service:
      type: NodePort
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn # gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
alertmanager:
  service:
    type: NodePort
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn # gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 1
    alertmanagerConfigMatcherStrategy:
      type: None