{
 "title": "Agent Logs",
 "tags": [ "Logs" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   },
   {
    "name": "log_category",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Antrea Logs by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (count_over_time({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs by log level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (log_level) (count_over_time({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs in Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Agent Logs count by Category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(agent_log_category) (count_over_time({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Antrea Log Count Time Series by Category and Log Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (agent_log_category, log_level) (count_over_time({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\" } | json  [$__range]))",
     "legendFormat": "{{log_level}} {{agent_log_category}} "
    }
   ]
  },
  {
   "title": "Antrea Rate Events per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"fluentbit\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m])) by (log_level)",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"fluentbit\", nodename=~\"$instance\", log_level=~\"$log_level\" } | json | line_format `{{.timestamp}} at node {{.nodename}} with level {{.log_level}} from subsystem {{.agent_log_category}} with message: {{.message}}`",
     "maxLines": 100
    }
   ]
  }
 ]
}