apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: observability
spec:
  route:
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HighCpuUsage
      receiver: 'send-email'
    - matchers:
      - name: alertname
        value: PodRestart
      receiver: 'send-email'
      repeatInterval: 5m
      
  receivers:
  - name: 'send-email'
    emailConfigs:
    - to: 'rtaparay2@gmail.com'
      from: 'rtaparay2@gmail.com'
      sendResolved: false
      smarthost: smtp.gmail.com:587
      authUsername: 'rtaparay2@gmail.com'
      authIdentity: 'rtaparay2@gmail.com'
      authPassword:
        name: mail-pass
        key: gmail-pass
