apiVersion: 1
datasources:
  # Loki Datasource using distributed deployment (otherwise use port 3100)
  - name: loki
    type: loki
    uid: loki
    url: http://loki-loki-distributed-gateway.observability.svc.cluster.local:80
    access: proxy
    version: 1
    editable: true
    
  # Prometheus Datasource
  # - name: Prometheus-2
  #   type: prometheus
  #   uid: prometheus
  #   url: http://observability-stack-kube-p-prometheus.observability:9090/
  #   access: proxy
  #   version: 1
  #   editable: true
  #   jsonData:
  #     httpMethod: POST
  #     timeInterval: 30s

  # Alertmanager Datasource
  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://observability-stack-kube-p-alertmanager.observability:9093/
    access: proxy
    version: 1
    editable: true
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
