# kind -- DaemonSet or Deployment
kind: DaemonSet

env:
    - name: NODE_NAME
      valueFrom:
          fieldRef:
              fieldPath: spec.nodeName

config:
    service: |
        [SERVICE]
            Daemon              Off
            Flush               {{ .Values.flush }}
            Log_Level           {{ .Values.logLevel }}
            Parsers_File        parsers.conf
            Parsers_File        custom_parsers.conf
            HTTP_Server         On
            HTTP_Listen         0.0.0.0
            HTTP_Port           {{ .Values.metricsPort }}
            Health_Check        On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/*.log
            Exclude_Path      *kube-*,*azure-*,*blackbox-exporter-*,*blobfuse-flexvol-*,*coredns-*,*istio-*,*node-exporter-*,*keyvault-flexvolume-*,*kiali-*,*fluent-bit*
            Parser            docker
            DB                /var/log/flb_kube.db
            Mem_Buf_Limit     10MB
            Skip_Long_Lines   On
            Refresh_Interval  10

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc.cluster.local:443
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On

        [FILTER]
            Name record_modifier
            Match *
            Record podname ${HOSTNAME}
            Record nodename ${NODE_NAME}

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
        # escribirá todos los registros en la pantalla
        [OUTPUT]
            name  stdout
            match *

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
        [PARSER]
            Name        docker_plain
            Format      regex
            Regex       ^(?<time>[^ ]*)\s+(?<stream>stdout|stderr)\s+(?<log>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
            Decode_Field_As  escaped_utf8 log

        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L

        [PARSER]
            Name        syslog
            Format      regex
            Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
            Time_Key    time
